-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE public."Users"
(
    id integer NOT NULL,
    email character varying(50) NOT NULL,
    password character varying(50) NOT NULL,
    password_again character varying(50) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public."Employers"
(
    user_id integer NOT NULL,
    company_name character varying(100) NOT NULL,
    web_address character varying(100) NOT NULL,
    phone_number character varying(50) NOT NULL,
    PRIMARY KEY (user_id)
);

CREATE TABLE public."Jobseekers"
(
    user_id integer NOT NULL,
    name character varying(50) NOT NULL,
    surname character varying(50) NOT NULL,
    identity_number character(11) NOT NULL,
    year_of_birth date NOT NULL,
    PRIMARY KEY (user_id)
);

CREATE TABLE public."System_Personnel"
(
    user_id integer NOT NULL,
    name character varying(50) NOT NULL,
    surname character varying(50) NOT NULL,
    PRIMARY KEY (user_id)
);

CREATE TABLE public."Vericification_System"
(
    id integer NOT NULL,
    email_vericification_code character varying(50) NOT NULL,
    is_confirmed_email boolean NOT NULL,
    confirmed_date_email date NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public."Verification_System_for_Jobseekers"
(
    id integer NOT NULL,
    jobseeker_id integer NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public."Vericification_System_for_Employers"
(
    id integer NOT NULL,
    employer_id integer NOT NULL,
    confirmed_system_personnel_id integer NOT NULL,
    is_confirmed_by_system boolean NOT NULL,
    corfirmed_date_system date NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public."Jobs"
(
    id integer NOT NULL,
    "position" character varying(50) NOT NULL,
    PRIMARY KEY (id)
);

ALTER TABLE public."Employers"
    ADD FOREIGN KEY (user_id)
    REFERENCES public."Users" (id)
    NOT VALID;


ALTER TABLE public."Jobseekers"
    ADD FOREIGN KEY (user_id)
    REFERENCES public."Users" (id)
    NOT VALID;


ALTER TABLE public."System_Personnel"
    ADD FOREIGN KEY (user_id)
    REFERENCES public."Users" (id)
    NOT VALID;


ALTER TABLE public."Vericification_System_for_Employers"
    ADD FOREIGN KEY (employer_id)
    REFERENCES public."Employers" (user_id)
    NOT VALID;


ALTER TABLE public."Vericification_System_for_Employers"
    ADD FOREIGN KEY (confirmed_system_personnel_id)
    REFERENCES public."System_Personnel" (user_id)
    NOT VALID;


ALTER TABLE public."Verification_System_for_Jobseekers"
    ADD FOREIGN KEY (jobseeker_id)
    REFERENCES public."Jobseekers" (user_id)
    NOT VALID;


ALTER TABLE public."Vericification_System_for_Employers"
    ADD FOREIGN KEY (id)
    REFERENCES public."Vericification_System" (id)
    NOT VALID;


ALTER TABLE public."Verification_System_for_Jobseekers"
    ADD FOREIGN KEY (id)
    REFERENCES public."Vericification_System" (id)
    NOT VALID;

END;